export const siteConfig = {
  person: "Hasnane Nawaz",
  name: "Hasnane Nawaz - Social Media Marketing Portfolio",
  role: "Social Media Marketer | Content & Growth Strategy",
  url: "https://hasnane-nawaz.vercel.app",
  email: "hasnanenawaz@gmail.com",
  phone: "+91 8269786782",
  location: "Durg, Chhattisgarh, India",
  description:
    "Portfolio of Hasnane Nawaz, a social media marketer and growth strategist building engaged communities, lead engines, and revenue-focused campaigns.",
  keywords: [
    "Hasnane Nawaz",
    "social media marketer",
    "growth strategist",
    "content strategy",
    "community growth",
    "lead generation",
    "Meta Ads",
    "Durg Chhattisgarh",
    "marketing portfolio",
  ],
  jsonLd: {
    "@context": "https://schema.org",
    "@type": "Person",
    name: "Hasnane Nawaz",
    jobTitle: "Social Media Marketer and Growth Strategist",
    email: "mailto:hasnanenawaz@gmail.com",
    telephone: "+91 8269786782",
    address: {
      "@type": "PostalAddress",
      addressLocality: "Durg",
      addressRegion: "Chhattisgarh",
      addressCountry: "IN",
    },
    knowsAbout: [
      "Social Media Marketing",
      "Lead Generation",
      "Content Strategy",
      "Community Growth",
      "Meta Ads",
      "Sales Operations",
    ],
  },
};
